# menghubungkan docker dengan data base
version: "3"

networks:
  app-tier:
  # untuk menghubungkan antar image
    driver: bridge

services:
  postgres:
    image: postgres:16.2-alpine3.19
    networks:
      - app-tier
    restart: always
    env_file:
      - ./.env
    environment:
      - PGPORT=5439
    ports:
      - 5439:5439
      # simpen database ke lokal computer ( container dimatikan datanya tetap ada)
    volumes : 
      - pg_data:/var/lib/postgresql/data

  app: 
    depends_on:
      - postgres
    build: .
    networks:
      - app-tier
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080

volumes:
  pg_data:
